### ISSUE TITLE
fixer.io api is no longer free

### ISSUE THREAD

**Issue by rp1231** [hdodov/conveuro#2]
Maybe an option  can be added to add your personal api key.

Because right now it stops working after the 100 free requests.

Also it seems to have become a part of apilayer
https://apilayer.com/marketplace/fixer-api#pricing

**Comment by hdodov** [comment]
I switched the extension to use https://exchangerate.host/. The new version is currently pending review on the Chrome Web Store. Watch out for version 1.2.1 - it contains the fix.

**Comment by hdodov** [comment]
It appears that the extension was approved and the new version 1.2.1 is live. I tested it and it works. @rp1231 does it work for you as well?

**Comment by hdodov** [comment]
Hey, @rp1231, sorry for the late reply… Could you shoot me an email at hello@dodov.dev? I want to ask you a few things regarding the browser extension.

**Comment by yandodov** [comment]
I've released [version 1.2.3 of the extension](https://chrome.google.com/webstore/detail/conveuro/hchlbehbbfdiogoeigibfgjpcmhogaop/). It should be working fine now.
